/// Generated by spider on 2025-10-04 23:46:09.467247

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ed_tech/core/constants/icon_path.dart';

void main() {
  test('icon_path assets test', () {
    expect(File(IconPath.iconAvatar).existsSync(), isTrue);
    expect(File(IconPath.iconBag).existsSync(), isTrue);
    expect(File(IconPath.iconBank).existsSync(), isTrue);
    expect(File(IconPath.iconBook).existsSync(), isTrue);
    expect(File(IconPath.iconChat).existsSync(), isTrue);
    expect(File(IconPath.iconDone).existsSync(), isTrue);
    expect(File(IconPath.iconFacebook).existsSync(), isTrue);
    expect(File(IconPath.iconFilter).existsSync(), isTrue);
    expect(File(IconPath.iconGoogle).existsSync(), isTrue);
    expect(File(IconPath.iconHome).existsSync(), isTrue);
    expect(File(IconPath.iconLogout).existsSync(), isTrue);
    expect(File(IconPath.iconMaster).existsSync(), isTrue);
    expect(File(IconPath.iconMenu).existsSync(), isTrue);
    expect(File(IconPath.iconModifiy).existsSync(), isTrue);
    expect(File(IconPath.iconPaypal).existsSync(), isTrue);
    expect(File(IconPath.iconSetting).existsSync(), isTrue);
    expect(File(IconPath.iconSun).existsSync(), isTrue);
    expect(File(IconPath.iconTwitter).existsSync(), isTrue);
  });
}
