/// Generated by spider on 2025-10-20 01:12:42.672175

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ed_tech/core/constants/image_path.dart';

void main() {
  test('image_path assets test', () {
    expect(File(ImagePath.imagUnion).existsSync(), isTrue);
    expect(File(ImagePath.imagePhone).existsSync(), isTrue);
    expect(File(ImagePath.imgCardBackground).existsSync(), isTrue);
    expect(File(ImagePath.imgForgotPassword).existsSync(), isTrue);
    expect(File(ImagePath.introStep1).existsSync(), isTrue);
    expect(File(ImagePath.introStep2).existsSync(), isTrue);
    expect(File(ImagePath.introStep3).existsSync(), isTrue);
    expect(File(ImagePath.persionLanguege).existsSync(), isTrue);
    expect(File(ImagePath.persionPaint).existsSync(), isTrue);
  });
}
