/// Generated by spider on 2025-09-22 23:34:33.010593

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ed_tech/core/constants/image_path.dart';

void main() {
  test('image_path assets test', () {
    expect(File(ImagePath.imgForgotPassword).existsSync(), isTrue);
  });
}
