// Generated by spider on 2025-10-04 00:43:42.885062

class IconPath {
  IconPath._();

  static const String iconBag = 'assets/icons/icon_bag.svg';
  static const String iconBook = 'assets/icons/icon_book.svg';
  static const String iconChat = 'assets/icons/icon_chat.svg';
  static const String iconDone = 'assets/icons/icon_done.svg';
  static const String iconFilter = 'assets/icons/icon_filter.svg';
  static const String iconGoogle = 'assets/icons/icon_google.svg';
  static const String iconHome = 'assets/icons/icon_home.svg';
  static const String iconLogout = 'assets/icons/icon_logout.svg';
  static const String iconMenu = 'assets/icons/icon_menu.svg';
  static const String iconSetting = 'assets/icons/icon_setting.svg';
  static const String iconSun = 'assets/icons/icon_sun.svg';
}
