// Generated by spider on 2025-12-14 22:22:10.671793

class IconPath {
  IconPath._();

  static const String appIcon = 'assets/icons/app_icon.png';
  static const String iconAssigment = 'assets/icons/icon_assigment.svg';
  static const String iconAvatar = 'assets/icons/icon_avatar.svg';
  static const String iconBag = 'assets/icons/icon_bag.svg';
  static const String iconBank = 'assets/icons/icon_bank.png';
  static const String iconBook = 'assets/icons/icon_book.svg';
  static const String iconChat = 'assets/icons/icon_chat.svg';
  static const String iconCredit = 'assets/icons/icon_credit.svg';
  static const String iconDone = 'assets/icons/icon_done.svg';
  static const String iconFacebook = 'assets/icons/icon_facebook.svg';
  static const String iconFilter = 'assets/icons/icon_filter.svg';
  static const String iconGoogle = 'assets/icons/icon_google.svg';
  static const String iconHistory = 'assets/icons/icon_history.svg';
  static const String iconHome = 'assets/icons/icon_home.svg';
  static const String iconLogout = 'assets/icons/icon_logout.svg';
  static const String iconMaster = 'assets/icons/icon_master.png';
  static const String iconMenu = 'assets/icons/icon_menu.svg';
  static const String iconModifiy = 'assets/icons/icon_modifiy.svg';
  static const String iconPaypal = 'assets/icons/icon_paypal.png';
  static const String iconRanking = 'assets/icons/icon_ranking.svg';
  static const String iconSetting = 'assets/icons/icon_setting.svg';
  static const String iconSun = 'assets/icons/icon_sun.svg';
  static const String iconTrash = 'assets/icons/icon_trash.svg';
  static const String iconTwitter = 'assets/icons/icon_twitter.svg';
}
