// Generated by spider on 2025-10-04 00:43:43.046755

class ImagePath {
  ImagePath._();

  static const String imgForgotPassword =
      'assets/images/img_forgot_password.svg';
  static const String introStep1 = 'assets/images/intro_step_1.svg';
  static const String introStep2 = 'assets/images/intro_step_2.svg';
  static const String introStep3 = 'assets/images/intro_step_3.svg';
  static const String persionLanguege = 'assets/images/persion_languege.svg';
  static const String persionPaint = 'assets/images/persion_paint.svg';
}
